"""dev_compare.py — generates a one-click Beyond Compare launcher next to a
sample clip's reference file, so a generated output can be eyeballed against
ground truth without hunting down paths by hand.

Tool-agnostic dev utility, not a runtime dependency between tools (same
pattern as srt_verify.py being imported by reel_subtitles.py) — any of the
three tools can call write_compare_script() once it has a reference file and
one or more candidate outputs to show against it. Nothing here is subtitle-
specific beyond the caller's own glob pattern.

Only ever called from the samples/-triggered dev-testing path (see
reel_subtitles.py) — real-clip usage never touches this.
"""
from __future__ import annotations

import os
from pathlib import Path

BCOMPARE_EXE = os.environ.get("REEL_BCOMPARE", r"C:\Program Files\Beyond Compare 5\BCompare.exe")

# BCompare's CLI opens a 3-way compare when given exactly 3 paths. Capping at
# 2 candidates (plus the reference) stays inside that well-known form; a 4th
# variant would need a second script or a manual invocation — not handled
# here since nothing currently produces more than 2 (cuda, cpu).
MAX_CANDIDATES = 2


def write_compare_script(
    clip_dir: Path,
    reference_path: Path,
    candidate_dir: Path,
    candidate_glob: str,
    script_name: str = "compare_in_beyond_compare.bat",
) -> Path | None:
    """(Re)writes clip_dir/script_name to open Beyond Compare on
    reference_path plus whatever currently matches candidate_glob in
    candidate_dir. Returns the script path, or None if nothing matches yet
    (e.g. only one of two devices has run so far — nothing to compare)."""
    if not candidate_dir.is_dir():
        return None

    all_matches = sorted(candidate_dir.glob(candidate_glob), key=lambda p: p.stat().st_mtime, reverse=True)
    candidates = sorted(all_matches[:MAX_CANDIDATES])  # most-recent N, then alphabetical for a stable display order
    if not candidates:
        return None

    clip_dir.mkdir(parents=True, exist_ok=True)
    paths = [reference_path, *candidates]
    quoted = " ".join(f'"{os.path.relpath(p, clip_dir)}"' for p in paths)

    script_path = clip_dir / script_name
    script_path.write_text(
        # chcp 65001 + utf-8: the embedded paths include the clip directory's
        # name and the candidate filenames, and nothing constrains those to
        # ASCII — a typographic dash or an accented character is enough.
        # Writing ascii raised UnicodeEncodeError and lost an otherwise-clean
        # subtitle run to a crash in a dev-convenience side effect. (This
        # tool's callers are the subtitle path, whose *sources* are
        # non-English; but the encoding hazard is the filename, not the
        # spoken language, and applies to any path.)
        "@echo off\r\n"
        "chcp 65001>nul\r\n"
        f"REM Generated by dev_compare.py - opens a {len(paths)}-way compare:\r\n"
        f"REM reference vs {', '.join(c.name for c in candidates)}.\r\n"
        f'"{BCOMPARE_EXE}" {quoted}\r\n',
        encoding="utf-8",
        newline="",  # the string already has explicit \r\n; don't let write_text double it up
    )
    return script_path
